// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udpphqttnvgrhnqjbrcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkcHBocXR0bnZncmhucWpicmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjgyMzMsImV4cCI6MjA2ODUwNDIzM30.mqGWqPvoiztalQKYw5Z4D1rpdPdDWstmeWpE0erO0gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});